import '../model/report_model.dart';

class ReportsRepository {
  Future<ReportModel> getReportsData() async {
    // Simulating network delay
    await Future.delayed(const Duration(milliseconds: 500));

    return ReportModel(
      monthlyVolume: [
        ChartDataPoint(label: 'Apr', value: 110, value2: 95),
        ChartDataPoint(label: 'May', value: 140, value2: 130),
        ChartDataPoint(label: 'Jun', value: 80, value2: 170),
        ChartDataPoint(label: 'Jul', value: 120, value2: 135),
        ChartDataPoint(label: 'Aug', value: 85, value2: 70),
        ChartDataPoint(label: 'Sep', value: 190, value2: 125),
        ChartDataPoint(label: 'Oct', value: 85, value2: 75),
        ChartDataPoint(label: 'Nov', value: 185, value2: 115),
        ChartDataPoint(label: 'Dec', value: 90, value2: 80),
        ChartDataPoint(label: 'Jan', value: 175, value2: 120),
        ChartDataPoint(label: 'Feb', value: 155, value2: 170),
        ChartDataPoint(label: 'Mar', value: 105, value2: 100),
      ],
      districtWise: [
        ChartDataPoint(label: 'Dehradun', value: 230),
        ChartDataPoint(label: 'Haridwar', value: 150),
        ChartDataPoint(label: 'Nainital', value: 200),
        ChartDataPoint(label: 'Tehri', value: 200),
        ChartDataPoint(label: 'Pauri', value: 260),
        ChartDataPoint(label: 'Almora', value: 80),
        ChartDataPoint(label: 'Uttarkashi', value: 75),
        ChartDataPoint(label: 'Chamoli', value: 130),
      ],
      stageDistribution: [
        ChartDataPoint(label: 'Submitted', value: 15),
        ChartDataPoint(label: 'Field Survey', value: 12),
        ChartDataPoint(label: 'Verification', value: 18),
        ChartDataPoint(label: 'Valuation', value: 10),
        ChartDataPoint(label: 'UKPCB', value: 8),
        ChartDataPoint(label: 'DM Approval', value: 5),
        ChartDataPoint(label: 'Treasury', value: 10),
        ChartDataPoint(label: 'Completed', value: 45),
      ],
      speciesCompensation: [
        ChartDataPoint(label: 'Deodar', value: 48),
        ChartDataPoint(label: 'Teak', value: 38),
        ChartDataPoint(label: 'Sal', value: 33),
        ChartDataPoint(label: 'Oak', value: 25),
        ChartDataPoint(label: 'Pine', value: 18),
        ChartDataPoint(label: 'Sissoo', value: 16),
        ChartDataPoint(label: 'Others', value: 12),
      ],
      compensationTrend: [
        ChartDataPoint(label: 'Apr', value: 5.0),
        ChartDataPoint(label: 'May', value: 4.7),
        ChartDataPoint(label: 'Jun', value: 6.0),
        ChartDataPoint(label: 'Jul', value: 3.5),
        ChartDataPoint(label: 'Aug', value: 5.0),
        ChartDataPoint(label: 'Sep', value: 4.0),
        ChartDataPoint(label: 'Oct', value: 1.8),
        ChartDataPoint(label: 'Nov', value: 1.2),
        ChartDataPoint(label: 'Dec', value: 1.5),
        ChartDataPoint(label: 'Jan', value: 2.7),
        ChartDataPoint(label: 'Feb', value: 1.5),
        ChartDataPoint(label: 'Mar', value: 2.2),
      ],
      slaPerformance: {
        'Forest Guard': 82,
        'Range Officer': 91,
        'DFO': 78,
        'UKPCB': 85,
        'DM': 88,
        'Treasury': 74,
      },
      treesMonthly: [
        ChartDataPoint(label: 'Apr', value: 560, value2: 1150),
        ChartDataPoint(label: 'May', value: 720, value2: 560),
        ChartDataPoint(label: 'Jun', value: 450, value2: 890),
        ChartDataPoint(label: 'Jul', value: 570, value2: 520),
        ChartDataPoint(label: 'Aug', value: 290, value2: 960),
        ChartDataPoint(label: 'Sep', value: 510, value2: 420),
        ChartDataPoint(label: 'Oct', value: 230, value2: 550),
        ChartDataPoint(label: 'Nov', value: 700, value2: 975),
        ChartDataPoint(label: 'Dec', value: 530, value2: 780),
        ChartDataPoint(label: 'Jan', value: 620, value2: 895),
        ChartDataPoint(label: 'Feb', value: 740, value2: 965),
        ChartDataPoint(label: 'Mar', value: 565, value2: 710),
      ],
      envIndexMonthly: [
        ChartDataPoint(label: 'Apr', value: 63),
        ChartDataPoint(label: 'May', value: 76),
        ChartDataPoint(label: 'Jun', value: 62),
        ChartDataPoint(label: 'Jul', value: 86),
        ChartDataPoint(label: 'Aug', value: 71),
        ChartDataPoint(label: 'Sep', value: 84),
        ChartDataPoint(label: 'Oct', value: 69),
        ChartDataPoint(label: 'Nov', value: 58),
        ChartDataPoint(label: 'Dec', value: 68),
        ChartDataPoint(label: 'Jan', value: 75),
        ChartDataPoint(label: 'Feb', value: 87),
        ChartDataPoint(label: 'Mar', value: 79),
      ],
      campaMonthly: [
        ChartDataPoint(label: 'Apr', value: 31, value2: 28),
        ChartDataPoint(label: 'May', value: 34, value2: 20),
        ChartDataPoint(label: 'Jun', value: 51, value2: 30),
        ChartDataPoint(label: 'Jul', value: 21, value2: 24),
        ChartDataPoint(label: 'Aug', value: 17, value2: 13),
        ChartDataPoint(label: 'Sep', value: 58, value2: 20),
        ChartDataPoint(label: 'Oct', value: 19, value2: 29),
        ChartDataPoint(label: 'Nov', value: 26, value2: 13),
        ChartDataPoint(label: 'Dec', value: 21, value2: 49),
        ChartDataPoint(label: 'Jan', value: 47, value2: 35),
        ChartDataPoint(label: 'Feb', value: 55, value2: 47),
        ChartDataPoint(label: 'Mar', value: 33, value2: 35),
      ],
      paymentFlowMonthly: [
        ChartDataPoint(label: 'Apr', value: 45, value2: 29),
        ChartDataPoint(label: 'May', value: 47, value2: 37),
        ChartDataPoint(label: 'Jun', value: 81, value2: 19),
        ChartDataPoint(label: 'Jul', value: 25, value2: 21),
        ChartDataPoint(label: 'Aug', value: 85, value2: 30),
        ChartDataPoint(label: 'Sep', value: 62, value2: 15),
        ChartDataPoint(label: 'Oct', value: 80, value2: 39),
        ChartDataPoint(label: 'Nov', value: 75, value2: 14),
        ChartDataPoint(label: 'Dec', value: 33, value2: 35),
        ChartDataPoint(label: 'Jan', value: 24, value2: 2),
        ChartDataPoint(label: 'Feb', value: 95, value2: 35),
        ChartDataPoint(label: 'Mar', value: 80, value2: 1),
      ],
    );
  }
}
