import 'package:flutter/material.dart';
import '../models/user_role.dart';
import '../models/nav_item.dart';

class RoleMenus {
  static const Map<UserRole, List<NavItem>> menus = {
    UserRole.applicant: [
      NavItem.section('My Portal'),
      NavItem.item(
        id: 'dashboard',
        icon: Icons.home_outlined,
        label: 'My Dashboard',
        route: '/home/dashboard',
      ),
      NavItem.item(
        id: 'new_application',
        icon: Icons.add_circle_outline,
        label: 'New Application',
        route: '/home/new_application',
        badge: 'New',
      ),
      NavItem.item(
        id: 'my_applications',
        icon: Icons.description_outlined,
        label: 'My Applications',
        route: '/home/my_applications',
        badge: '3',
      ),
      NavItem.item(
        id: 'payment_status',
        icon: Icons.currency_rupee,
        label: 'Payment Status',
        route: '/home/payment_status',
      ),
      NavItem.item(
        id: 'documents',
        icon: Icons.folder_outlined,
        label: 'My Documents',
        route: '/home/documents',
      ),
      NavItem.section('Support'),
      NavItem.item(
        id: 'grievance',
        icon: Icons.headset_mic_outlined,
        label: 'Grievance',
        route: '/home/grievance',
      ),
      NavItem.item(
        id: 'notifications',
        icon: Icons.notifications_outlined,
        label: 'Notifications',
        route: '/home/notifications',
        badge: '2',
      ),
    ],
    UserRole.forestGuard: [
      NavItem.section('Field Operations'),
      NavItem.item(
        id: 'dashboard',
        icon: Icons.home_outlined,
        label: 'Dashboard',
        route: '/home/dashboard',
      ),
      NavItem.item(
        id: 'assigned_surveys',
        icon: Icons.assignment_outlined,
        label: 'Assigned Surveys',
        route: '/home/geo_tagging',
        badge: '5',
        isAlertBadge: true,
      ),
      NavItem.item(
        id: 'geo_tagging',
        icon: Icons.location_on_outlined,
        label: 'Geo-Tagging & Survey',
        route: '/home/geo_tagging',
      ),
      NavItem.item(
        id: 'tree_enumeration',
        icon: Icons.park_outlined,
        label: 'Tree Enumeration',
        route: '/home/tree_enumeration',
      ),
      NavItem.item(
        id: 'gis_map',
        icon: Icons.map_outlined,
        label: 'GIS Map',
        route: '/home/gis_map',
      ),
      NavItem.section('Reports'),
      NavItem.item(
        id: 'field_reports',
        icon: Icons.picture_as_pdf_outlined,
        label: 'Field Reports',
        route: '/home/reports',
      ),
      NavItem.item(
        id: 'activity_log',
        icon: Icons.history,
        label: 'Daily Activity',
        route: '/home/audit',
      ),
    ],
    UserRole.rangeOfficer: [
      NavItem.section('Verification Queue'),
      NavItem.item(
        id: 'dashboard',
        icon: Icons.home_outlined,
        label: 'Dashboard',
        route: '/home/dashboard',
      ),
      NavItem.item(
        id: 'verification_queue',
        icon: Icons.rule_outlined,
        label: 'Pending Verification',
        route: '/home/verification_queue',
        badge: '8',
        isAlertBadge: true,
      ),
      NavItem.item(
        id: 'field_discrepancy',
        icon: Icons.error_outline,
        label: 'Discrepancy Alerts',
        route: '/home/verification_queue',
        badge: '2',
        isAlertBadge: true,
      ),
      NavItem.item(
        id: 'my_applications',
        icon: Icons.description_outlined,
        label: 'All Applications',
        route: '/home/my_applications',
      ),
      NavItem.item(
        id: 'gis_map',
        icon: Icons.map_outlined,
        label: 'GIS Overview',
        route: '/home/gis_map',
      ),
      NavItem.section('Analytics'),
      NavItem.item(
        id: 'reports',
        icon: Icons.bar_chart_outlined,
        label: 'Reports & Analytics',
        route: '/home/reports',
      ),
    ],
    UserRole.dfo: [
      NavItem.section('DFO Operations'),
      NavItem.item(
        id: 'dashboard',
        icon: Icons.home_outlined,
        label: 'DFO Dashboard',
        route: '/home/dashboard',
      ),
      NavItem.item(
        id: 'valuation_approvals',
        icon: Icons.approval_outlined,
        label: 'Valuation Approvals',
        route: '/home/my_applications',
        badge: '12',
        isAlertBadge: true,
      ),
      NavItem.item(
        id: 'compensation_calc',
        icon: Icons.calculate_outlined,
        label: 'Compensation Engine',
        route: '/home/compensation_calc',
      ),
      NavItem.item(
        id: 'high_value_cases',
        icon: Icons.star_outline,
        label: 'High-Value Cases',
        route: '/home/my_applications',
      ),
      NavItem.item(
        id: 'my_applications',
        icon: Icons.description_outlined,
        label: 'All Applications',
        route: '/home/my_applications',
      ),
      NavItem.item(
        id: 'gis_map',
        icon: Icons.map_outlined,
        label: 'District GIS Map',
        route: '/home/gis_map',
      ),
      NavItem.section('Analytics'),
      NavItem.item(
        id: 'reports',
        icon: Icons.bar_chart_outlined,
        label: 'Compensation Analytics',
        route: '/home/reports',
      ),
      NavItem.item(
        id: 'ai_insights',
        icon: Icons.psychology_outlined,
        label: 'AI Insights',
        route: '/home/ai_insights',
      ),
    ],
    UserRole.ukpcb: [
      NavItem.section('UKPCB Portal'),
      NavItem.item(
        id: 'dashboard',
        icon: Icons.home_outlined,
        label: 'UKPCB Dashboard',
        route: '/home/dashboard',
      ),
      NavItem.item(
        id: 'compliance_queue',
        icon: Icons.verified_user_outlined,
        label: 'Compliance Queue',
        route: '/home/compliance',
        badge: '6',
        isAlertBadge: true,
      ),
      NavItem.item(
        id: 'env_clearance',
        icon: Icons.eco_outlined,
        label: 'Env. Clearance Track',
        route: '/home/my_applications',
      ),
      NavItem.item(
        id: 'high_risk',
        icon: Icons.warning_amber_outlined,
        label: 'High-Risk Projects',
        route: '/home/my_applications',
        badge: '3',
        isAlertBadge: true,
      ),
      NavItem.item(
        id: 'pollution_cases',
        icon: Icons.cloud_outlined,
        label: 'Pollution-Linked Cases',
        route: '/home/my_applications',
      ),
      NavItem.item(
        id: 'gis_map',
        icon: Icons.map_outlined,
        label: 'Environmental GIS',
        route: '/home/gis_map',
      ),
      NavItem.section('Reports'),
      NavItem.item(
        id: 'reports',
        icon: Icons.bar_chart_outlined,
        label: 'Compliance Reports',
        route: '/home/reports',
      ),
      NavItem.item(
        id: 'ai_insights',
        icon: Icons.psychology_outlined,
        label: 'AI Risk Scoring',
        route: '/home/ai_insights',
      ),
    ],
    UserRole.dm: [
      NavItem.section('DM Office'),
      NavItem.item(
        id: 'dashboard',
        icon: Icons.home_outlined,
        label: 'DM Dashboard',
        route: '/home/dashboard',
      ),
      NavItem.item(
        id: 'final_approvals',
        icon: Icons.gavel_outlined,
        label: 'Final Approvals',
        route: '/home/my_applications',
        badge: '4',
        isAlertBadge: true,
      ),
      NavItem.item(
        id: 'district_summary',
        icon: Icons.place_outlined,
        label: 'District Summary',
        route: '/home/reports',
      ),
      NavItem.item(
        id: 'sla_compliance',
        icon: Icons.timer_outlined,
        label: 'SLA Compliance',
        route: '/home/workflow',
      ),
      NavItem.item(
        id: 'gis_map',
        icon: Icons.map_outlined,
        label: 'District GIS',
        route: '/home/gis_map',
      ),
      NavItem.section('Intelligence'),
      NavItem.item(
        id: 'reports',
        icon: Icons.bar_chart_outlined,
        label: 'Reports',
        route: '/home/reports',
      ),
      NavItem.item(
        id: 'ai_insights',
        icon: Icons.psychology_outlined,
        label: 'AI Decision Support',
        route: '/home/ai_insights',
      ),
      NavItem.item(
        id: 'command_center',
        icon: Icons.tv_outlined,
        label: 'Command Center',
        route: '/home/command_center',
      ),
    ],
    UserRole.treasury: [
      NavItem.section('Treasury Portal'),
      NavItem.item(
        id: 'dashboard',
        icon: Icons.home_outlined,
        label: 'Treasury Dashboard',
        route: '/home/dashboard',
      ),
      NavItem.item(
        id: 'payment_pending',
        icon: Icons.pending_outlined,
        label: 'Payments Pending',
        route: '/home/payment_status',
        badge: '9',
        isAlertBadge: true,
      ),
      NavItem.item(
        id: 'challan_gen',
        icon: Icons.receipt_outlined,
        label: 'Challan Generation',
        route: '/home/payment_status',
      ),
      NavItem.item(
        id: 'payment_status',
        icon: Icons.check_circle_outline,
        label: 'Payment Status',
        route: '/home/payment_status',
      ),
      NavItem.item(
        id: 'campa_fund',
        icon: Icons.savings_outlined,
        label: 'CAMPA Fund Track',
        route: '/home/payment_status',
      ),
      NavItem.section('Reports'),
      NavItem.item(
        id: 'reports',
        icon: Icons.bar_chart_outlined,
        label: 'Financial Reports',
        route: '/home/reports',
      ),
    ],
    UserRole.admin: [
      NavItem.section('Command & Control'),
      NavItem.item(
        id: 'dashboard',
        icon: Icons.home_outlined,
        label: 'Executive Dashboard',
        route: '/home/dashboard',
      ),
      NavItem.item(
        id: 'command_center',
        icon: Icons.tv_outlined,
        label: 'Command Center',
        route: '/home/command_center',
        badge: 'LIVE',
        isAlertBadge: true,
      ),
      NavItem.item(
        id: 'ai_insights',
        icon: Icons.psychology_outlined,
        label: 'AI Decision Support',
        route: '/home/ai_insights',
      ),
      NavItem.item(
        id: 'gis_map',
        icon: Icons.satellite_alt_outlined,
        label: 'GIS & Satellite View',
        route: '/home/gis_map',
      ),
      NavItem.section('All Modules'),
      NavItem.item(
        id: 'my_applications',
        icon: Icons.description_outlined,
        label: 'All Applications',
        route: '/home/my_applications',
      ),
      NavItem.item(
        id: 'workflow_engine',
        icon: Icons.account_tree_outlined,
        label: 'Workflow Engine',
        route: '/home/workflow',
      ),
      NavItem.item(
        id: 'compensation_calc',
        icon: Icons.calculate_outlined,
        label: 'Valuation Engine',
        route: '/home/compensation_calc',
      ),
      NavItem.item(
        id: 'approval_queue',
        icon: Icons.tag_outlined,
        label: 'Approval Queue',
        route: '/home/verification_queue',
      ),
      NavItem.item(
        id: 'payment_status',
        icon: Icons.currency_rupee,
        label: 'Payment & Treasury',
        route: '/home/payment_status',
      ),
      NavItem.item(
        id: 'documents',
        icon: Icons.folder_outlined,
        label: 'DMS',
        route: '/home/documents',
      ),
      NavItem.item(
        id: 'compliance_queue',
        icon: Icons.verified_user_outlined,
        label: 'UKPCB Compliance',
        route: '/home/compliance',
      ),
      NavItem.item(
        id: 'grievance',
        icon: Icons.headset_mic_outlined,
        label: 'Grievance Portal',
        route: '/home/grievance',
      ),
      NavItem.section('Analytics & Admin'),
      NavItem.item(
        id: 'reports',
        icon: Icons.bar_chart_outlined,
        label: 'Reports & Analytics',
        route: '/home/reports',
      ),
      NavItem.item(
        id: 'user_mgmt',
        icon: Icons.manage_accounts_outlined,
        label: 'User Management',
        route: '/home/user_mgmt',
      ),
      NavItem.item(
        id: 'audit',
        icon: Icons.history,
        label: 'Audit Trail',
        route: '/home/audit',
      ),
      NavItem.item(
        id: 'settings',
        icon: Icons.settings_outlined,
        label: 'System Settings',
        route: '/home/settings',
      ),
    ],
  };
}
